import {env} from 'cloudflare:workers';
import {byId} from '@/lib/catalogue';
function db(){const v=(env as unknown as {DB:D1Database}).DB;if(!v)throw Error('Storage unavailable');return v}
function identity(req:Request){const auth=req.headers.get('oai-authenticated-user-id');if(auth)return{owner:'user:'+auth,cookie:''};const match=(req.headers.get('cookie')||'').match(/(?:^|; )stride_session=([a-f0-9-]{36})(?:;|$)/);const id=match?.[1]||crypto.randomUUID();return{owner:'guest:'+id,cookie:match?'':`stride_session=${id}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${new URL(req.url).protocol==='https:'?'; Secure':''}`}}
function out(data:unknown,cookie='',status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store',...(cookie?{'Set-Cookie':cookie}:{})}})}
export async function GET(req:Request){const {owner,cookie}=identity(req);try{const r=await db().batch([db().prepare('SELECT product,quantity FROM basket WHERE owner=?').bind(owner),db().prepare('SELECT product FROM saved WHERE owner=?').bind(owner),db().prepare('SELECT data FROM profiles WHERE owner=?').bind(owner),db().prepare('SELECT * FROM requests WHERE owner=? ORDER BY created DESC LIMIT 100').bind(owner),db().prepare('SELECT * FROM plans WHERE owner=? ORDER BY created DESC LIMIT 50').bind(owner)]);return out({cart:r[0].results.map((x:any)=>({...x,item:byId.get(x.product)})),saved:r[1].results.map((x:any)=>x.product),profile:r[2].results[0]?JSON.parse(String((r[2].results[0] as any).data)):{},requests:r[3].results.map((x:any)=>({...x,data:JSON.parse(x.data)})),plans:r[4].results.map((x:any)=>({...x,data:JSON.parse(x.data)})),email:req.headers.get('oai-authenticated-user-email')},cookie)}catch(e){console.error(e);return out({error:'Saved shopping information is temporarily unavailable. Please retry.'},cookie,503)}}
export async function POST(req:Request){const {owner,cookie}=identity(req);try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return out({error:'Invalid origin'},cookie,403);const raw=await req.text();if(raw.length>30000)return out({error:'Request too large'},cookie,413);const b=JSON.parse(raw);const action=b.action;
if(action==='cart'){if(!byId.has(b.product)||!Number.isInteger(b.quantity)||b.quantity<0||b.quantity>50)return out({error:'Select a product and quantity from 1 to 50.'},cookie,400);if(b.quantity===0)await db().prepare('DELETE FROM basket WHERE owner=? AND product=?').bind(owner,b.product).run();else await db().prepare('INSERT INTO basket(owner,product,quantity) VALUES(?,?,?) ON CONFLICT(owner,product) DO UPDATE SET quantity=excluded.quantity').bind(owner,b.product,b.quantity).run();}
else if(action==='save'){if(!byId.has(b.product))return out({error:'Product not found'},cookie,400);if(b.value)await db().prepare('INSERT OR IGNORE INTO saved(owner,product) VALUES(?,?)').bind(owner,b.product).run();else await db().prepare('DELETE FROM saved WHERE owner=? AND product=?').bind(owner,b.product).run();}
else if(action==='profile'){const p=b.profile||{},data=Object.fromEntries(['name','email','phone','city','address','digitalAddress'].map(k=>[k,String(p[k]||'').slice(0,300)]));await db().prepare('INSERT INTO profiles(owner,data) VALUES(?,?) ON CONFLICT(owner) DO UPDATE SET data=excluded.data').bind(owner,JSON.stringify(data)).run();}
else if(action==='plan'){if(typeof b.name!=='string'||!b.name.trim()||!Array.isArray(b.items)||b.items.length>60||b.items.some((v:unknown)=>typeof v!=='string'||v.length>1000))return out({error:'Add a plan name and up to 60 entries.'},cookie,400);const id='PL-'+crypto.randomUUID();await db().prepare('INSERT INTO plans(id,owner,name,data,created) VALUES(?,?,?,?,?)').bind(id,owner,String(b.name).slice(0,120),JSON.stringify({type:String(b.type||'workout'),items:b.items}),new Date().toISOString()).run();return out({ok:true,id},cookie);}
else if(action==='delete-plan'){await db().prepare('DELETE FROM plans WHERE id=? AND owner=?').bind(String(b.id),owner).run();}
else if(action==='request'){if(!['quote','service','business','support','return','supplier'].includes(b.kind))return out({error:'Invalid request type'},cookie,400);const f=b.form||{};if(!String(f.name||'').trim()||!/^\S+@\S+\.\S+$/.test(String(f.email||'')))return out({error:'Enter your name and a valid email.'},cookie,400);const data:any=Object.fromEntries(['name','email','phone','city','address','digitalAddress','message','service','paymentPreference'].map(k=>[k,String(f[k]||'').slice(0,k==='message'?3000:300)]));if(b.kind==='quote'){const r=await db().prepare('SELECT product,quantity FROM basket WHERE owner=?').bind(owner).all();data.items=r.results.map((x:any)=>{const p=byId.get(x.product);return p?{id:p.id,name:p.name,quantity:x.quantity,guidePrice:p.priceGHS}:null}).filter(Boolean);if(!data.items.length)return out({error:'Your bag is empty.'},cookie,400);data.total=data.items.reduce((s:number,x:any)=>s+(x.guidePrice||0)*x.quantity,0);data.priceType='Planning estimate; not a selling price';data.paymentStatus='No payment taken';}const key=String(b.idempotencyKey||'');if(!/^[a-f0-9-]{36}$/.test(key))return out({error:'Refresh the form and try again.'},cookie,400);const id='ST-'+key;const old=await db().prepare('SELECT id FROM requests WHERE id=? AND owner=?').bind(id,owner).first();if(!old)await db().prepare('INSERT INTO requests(id,owner,kind,data,status,created) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,owner,b.kind,JSON.stringify(data),'Saved — awaiting store launch',new Date().toISOString()).run();const stored=await db().prepare('SELECT id FROM requests WHERE id=? AND owner=?').bind(id,owner).first();if(!stored)return out({error:'Please reopen the form to create a new request.'},cookie,409);return out({ok:true,id},cookie);}
else return out({error:'Unknown action'},cookie,400);return out({ok:true},cookie)}catch(e){console.error(e);return out({error:'We could not save this change. Your form is retained; please retry.'},cookie,503)}}
