'use client';
import {useState} from 'react';
import {ArrowRight,ShieldCheck,Mail,LogOut,MonitorSmartphone} from 'lucide-react';

export type AccountUser={id:string;email:string;name?:string;emailVerified:boolean};
async function authPost(path:string,body:unknown){
 const response=await fetch('/api/auth/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 const data:any=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(data.message||data.error||'Please try again in a moment.');
 return data;
}
export default function AccountAccess({user,enabled,onChange,onAdmin}:{user?:AccountUser|null;enabled:boolean;onChange:()=>Promise<void>;onAdmin:()=>void}){
 const [email,setEmail]=useState(''),[code,setCode]=useState(''),[step,setStep]=useState<'email'|'code'>('email'),[pending,setPending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[sentAt,setSentAt]=useState(0);
 const action=async(work:()=>Promise<void>)=>{setPending(true);setError('');setNotice('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setPending(false)}};
 if(user)return <section className="account-access signed-in"><div className="account-access-copy"><ShieldCheck size={30}/><span className="eyebrow">YOUR ACCOUNT</span><h2>Your progress.<br/>In one place.</h2><p>Signed in as <strong>{user.email}</strong>. Your bag, favourites, requests and plans follow you across devices.</p></div><div className="account-access-form"><h3>Account security</h3><p>Sign in with a short-lived email code. There is no password to remember or reset.</p><button className="button outline-button" disabled={pending} onClick={()=>action(async()=>{await authPost('revoke-other-sessions',{});setNotice('Other devices have been signed out.');})}><MonitorSmartphone size={18}/>Sign out other devices</button><button className="button dark-button" disabled={pending} onClick={()=>action(async()=>{await authPost('sign-out',{});await onChange();})}><LogOut size={18}/>Sign out</button><button className="text-button" onClick={onAdmin}>Staff workspace</button>{error&&<p role="alert" className="auth-error">{error}</p>}{notice&&<p role="status">{notice}</p>}</div></section>;
 return <section className="account-access"><div className="account-access-copy"><ShieldCheck size={30}/><span className="eyebrow">MAKE IT YOURS</span><h2>A little more you.<br/>Every time you return.</h2><p>Keep your favourites, gym plans and quotations together. Sign in securely with a code sent to your email.</p><span className="account-access-note">Your current bag and saved items come with you.</span></div><div className="account-access-form">{enabled?<form onSubmit={e=>{e.preventDefault();action(async()=>{if(step==='email'){await authPost('email-otp/send-verification-otp',{email:email.trim(),type:'sign-in'});setStep('code');setSentAt(Date.now());setNotice('Check your inbox for your sign-in code. It expires in five minutes.');}else{await authPost('sign-in/email-otp',{email:email.trim(),otp:code.trim()});setCode('');await onChange();}});}}><Mail size={24}/><h3>{step==='email'?'Welcome to your STRIDE.':'Check your inbox.'}</h3>{step==='email'?<label>Email address<input autoComplete="email" name="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254} placeholder="you@example.com" disabled={pending}/></label>:<><p>Enter the code sent to <strong>{email}</strong>.</p><label>Sign-in code<input name="otp" autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{8}" maxLength={8} minLength={8} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required disabled={pending} className="otp-input"/></label><button type="button" className="text-button" disabled={pending} onClick={()=>{setStep('email');setCode('');setError('');setNotice('')}}>Use another email</button><button type="button" className="text-button" disabled={pending} onClick={()=>action(async()=>{if(Date.now()-sentAt<60000)throw new Error('Please wait a minute before requesting another code.');await authPost('email-otp/send-verification-otp',{email:email.trim(),type:'sign-in'});setSentAt(Date.now());setNotice('A new code has been requested. Use the latest code in your inbox.');})}>Resend code</button></>}<button className="button orange-button" disabled={pending}>{pending?'One moment…':step==='email'?'Email me a sign-in code':'Verify & continue'}<ArrowRight size={18}/></button><p className="muted">By continuing, you agree to our <a href="/terms">terms</a> and <a href="/privacy">privacy notice</a>.</p>{error&&<p className="auth-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</form>:<><h3>Your guest space is ready.</h3><p>Accounts are being connected. You can browse, save favourites and build plans in this browser now.</p><p className="muted">Guest access depends on this browser’s cookie. Keep a copy of important request references until sign-in is available.</p></>}</div></section>;
}
