'use client';
import React, {useEffect, useState} from 'react';
import {ArrowLeft, ArrowRight, ArrowUpRight, Dumbbell, Footprints, Activity, Building2, Scale, ShieldCheck, MapPin, Plus, Check} from 'lucide-react';
import type {Product} from '@/lib/catalogue';
import edit from '@/data/storefront-edit.json';

type Department = {id:string;name:string;count:number;image?:string};
type Props = {departments:Department[];products:Product[];ProductCard:React.ComponentType<{p:Product}>;nav:(url:string)=>void;add:(p:Product)=>Promise<void>;busy:boolean;money:(n:number|null|undefined)=>string;request:(kind:string,service?:string)=>void};
const collections=[{id:'',name:'The essentials'},{id:'strength',name:'Strength'},{id:'protein',name:'Nutrition'},{id:'footwear',name:'Running'},{id:'recovery',name:'Recovery'}];
const featured=edit.hero as Product[];
const heroCopy=[{label:'THE STRENGTH EDIT',title:'Less space.\nMore possibility.'},{label:'THE CARDIO EDIT',title:'Find your pace.\nOwn your distance.'},{label:'THE RECOVERY EDIT',title:'A better reset.\nA stronger return.'}];
const departmentLabels:Record<string,string>={strength:'Strength',cardio:'Cardio',protein:'Nutrition',womens:'Activewear',footwear:'Footwear',recovery:'Recovery',yoga:'Yoga & Pilates',wearables:'Fitness tech'};
export default function ThemeHome({departments,products,ProductCard,nav,add,busy,money,request}:Props){
 const [spotlight,setSpotlight]=useState(0),[collection,setCollection]=useState(''),[items,setItems]=useState<Product[]>([]),[pending,setPending]=useState(false),[error,setError]=useState(false);
 const [retry,setRetry]=useState(0);
 useEffect(()=>{if(!collection){setItems(products.slice(0,4));setPending(false);setError(false);return}const controller=new AbortController();setPending(true);setError(false);fetch('/api/catalog?department='+collection+'&limit=4',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then((d:any)=>{setItems(d.products);setPending(false)}).catch(e=>{if(e.name!=='AbortError'){setError(true);setPending(false)}});return()=>controller.abort()},[collection,products,retry]);
 const p=featured[spotlight],copy=heroCopy[spotlight];
 const shop=(id:string)=>nav('/shop?department='+id);
 const categoryItems=Object.keys(departmentLabels).map(id=>departments.find(d=>d.id===id)).filter(Boolean) as Department[];
 return <div className="theme-home">
  <section className="shop-hero" aria-label="STRIDE collections">
   <article className="athlete-story">
    <img src="/images/hero-sprinter.webp" alt="Athlete accelerating on an indoor running track" fetchPriority="high"/>
    <div className="story-label"><span>STRIDE / GHANA</span><span>EVERY BODY. EVERY AMBITION.</span></div>
    <div className="story-copy"><span className="story-kicker">Your next starts here.</span><h1>Built for<br/><em>more.</em></h1><p>Equipment. Nutrition. Everyday essentials.<br/>Everything for the way you move.</p><button className="button orange-button" onClick={()=>nav('/shop')}>Explore the collection <ArrowUpRight size={19}/></button></div>
    <div className="story-foot"><span>6,272 products. One destination.</span><button onClick={()=>nav('/departments')} aria-label="Browse all departments"><ArrowUpRight size={25}/></button></div>
   </article>
   <article className="product-spotlight" aria-label="Equipment spotlight" aria-roledescription="carousel">
    <div className="spotlight-heading" key={copy.label}><span className="eyebrow">{copy.label}</span><h2>{copy.title.split('\n').map((s,i)=><React.Fragment key={s}>{i>0&&<br/>}{s}</React.Fragment>)}</h2></div>
    <button className="spotlight-image" onClick={()=>nav('/product/'+p.id)} aria-label={'Explore '+p.name}><span aria-hidden="true">{['LIFT','MOVE','RESET'][spotlight]}</span><img key={p.id} src={p.image} alt={p.name}/></button>
    <div className="spotlight-detail" aria-live="polite"><span>{p.brand}</span><h3>{p.name}</h3><strong>{money(p.priceGHS)}</strong><small>{p.sourceCurrency==='GHS'?'Ghana reference price':'Planning estimate'}</small></div>
    <div className="spotlight-actions"><button className="button dark-button" onClick={()=>nav('/product/'+p.id)}>Explore</button><button className="button outline-button" disabled={busy} onClick={()=>add(p)}>Add to bag <Plus size={16}/></button></div>
    <div className="spotlight-controls"><button onClick={()=>setSpotlight((spotlight+2)%3)} aria-label="Previous featured product"><ArrowLeft size={17}/></button><div>{featured.map((v,i)=><button key={v.id} className={i===spotlight?'active':''} onClick={()=>setSpotlight(i)} aria-label={'Show featured product '+(i+1)} aria-pressed={i===spotlight}/>)}</div><button onClick={()=>setSpotlight((spotlight+1)%3)} aria-label="Next featured product"><ArrowRight size={17}/></button></div>
   </article>
  </section>
  <div className="benefit-line"><span><Dumbbell size={18}/>22 departments</span><span><MapPin size={18}/>Built around Ghana</span><span><ShieldCheck size={18}/>Visible product sources</span><span><Activity size={18}/>5 practical training tools</span></div>
  <section className="section visual-departments"><div className="compact-heading"><h2>Find your movement.</h2><button onClick={()=>nav('/departments')}>All departments <ArrowUpRight size={18}/></button></div><div className="department-carousel">{categoryItems.map(d=><button key={d.id} onClick={()=>shop(d.id)}><div><img src={d.image} alt="" loading="lazy"/></div><strong>{departmentLabels[d.id]}</strong><span>{d.count.toLocaleString()} products</span></button>)}</div></section>
  <section className="section curated-products"><div className="compact-heading"><div><span className="eyebrow">YOUR EVERYDAY LINE-UP</span><h2>Good gear.<br/><span>Great beginnings.</span></h2></div><button onClick={()=>nav('/shop')}>View all products <ArrowUpRight size={18}/></button></div><div className="collection-tabs" role="group" aria-label="Featured collections">{collections.map(c=><button key={c.id} aria-pressed={collection===c.id} className={collection===c.id?'active':''} onClick={()=>setCollection(c.id)}>{c.name}</button>)}</div><div aria-busy={pending}>{pending?<div className="loading-grid">{[1,2,3,4].map(n=><div key={n}/>)}</div>:error?<div className="empty-state"><p>We couldn’t load this collection.</p><button className="button dark-button" onClick={()=>setRetry(retry+1)}>Try again</button></div>:<div className="product-grid home-products">{items.map(p=><ProductCard key={p.id} p={p}/>)}</div>}</div><p className="collection-note">Prices are sourcing references. Request a quote for final STRIDE pricing and availability.</p></section>
  <section className="section lifestyle-duo" aria-label="Apparel and recovery collections"><article className="lifestyle-tile apparel-tile"><img src="/images/apparel-editorial.webp" alt="Athlete wearing charcoal leggings and a grey training top" loading="lazy"/><div><span className="eyebrow">FIT FOR YOUR EVERYDAY</span><h2>Comfort in<br/>every move.</h2><button className="button light-button" onClick={()=>shop('womens')}>Explore activewear <ArrowUpRight size={18}/></button></div></article><article className="lifestyle-tile recovery-tile"><img src="/images/recovery-studio.webp" alt="Massage gun, textured foam roller and resistance band" loading="lazy"/><div><span className="eyebrow">REST DAYS COUNT TOO</span><h2>Switch off.<br/>Come back stronger.</h2><button className="button light-button" onClick={()=>shop('recovery')}>Discover recovery <ArrowUpRight size={18}/></button></div></article></section>
  <section className="section nutrition-edit"><div className="nutrition-photo"><img src="/images/nutrition.webp" alt="Sports nutrition concept with protein, oats and a shaker" loading="lazy"/></div><div className="nutrition-copy"><span className="eyebrow">THE DAILY FOUNDATION</span><h2>Fuel the effort.<br/><em>Enjoy the progress.</em></h2><p>From protein and hydration to everyday nutrition. Explore the essentials that fit into your routine.</p><div>{[['Protein & shakes','protein'],['Vitamins & minerals','vitamins'],['Hydration essentials','hydration']].map(([name,id])=><button key={id} onClick={()=>shop(id)}>{name}<ArrowUpRight size={20}/></button>)}</div><button className="button dark-button" onClick={()=>shop('supplements')}>Explore sports nutrition</button></div></section>
  <section className="space-edit"><div className="space-photo"><img src="/images/strength.webp" alt="Premium home gym with free weights, power rack and natural light" loading="lazy"/></div><div className="space-copy"><span className="eyebrow">SMALL SPACE. BIG INTENTIONS.</span><h2>Your space.<br/>Your strength.</h2><p>A corner of your home or a full training floor. Plan the equipment, budget and room around your ambition.</p><div className="space-points"><span><Check size={17}/>Equipment shortlist</span><span><Check size={17}/>Room & budget planning</span><span><Check size={17}/>Save your gym plan</span></div><div><button className="button orange-button" onClick={()=>nav('/tools?tool=gym')}>Build your home gym <ArrowUpRight size={18}/></button><button className="space-shop" onClick={()=>shop('strength')}>Shop equipment <ArrowRight size={17}/></button></div></div></section>
  <section className="section movement-directory"><div className="compact-heading"><div><span className="eyebrow">THE COMPLETE COLLECTION</span><h2>Every way to move.<br/><span>All in one place.</span></h2></div><button onClick={()=>nav('/departments')}>Every category <ArrowUpRight size={18}/></button></div><div className="department-index">{departments.map((d,i)=><button key={d.id} onClick={()=>shop(d.id)}><span className="index-number">{String(i+1).padStart(2,'0')}</span><div><strong>{d.name}</strong><small>{d.count.toLocaleString()} products</small></div><ArrowUpRight size={19}/></button>)}</div></section>
  <section className="section training-edit"><div className="training-intro"><span className="eyebrow">THE STRIDE STUDIO</span><h2>A little structure.<br/>A lot of possibility.</h2><p>Make your next session count with tools for your training, equipment and time.</p><button className="button dark-button" onClick={()=>nav('/tools')}>Explore the studio <ArrowUpRight size={18}/></button></div><div className="studio-links">{[[Dumbbell,'Build your week','Workout builder','workout'],[Building2,'Make room for progress','Home gym planner','gym'],[Scale,'Every kilo counts','Plate calculator','plates'],[Activity,'Find your rhythm','Interval timer','timer'],[Footprints,'Go the distance','Running pace','pace']].map(([Icon,title,desc,id]:any)=><button key={id} onClick={()=>nav('/tools?tool='+id)}><Icon size={25}/><div><strong>{title}</strong><span>{desc}</span></div><ArrowUpRight size={20}/></button>)}</div></section>
  <section className="section business-strip"><div><span className="eyebrow">FOR BIGGER AMBITIONS</span><h2>Equip your gym.<br/>Empower your team.</h2></div><div><p>Commercial gyms, schools, clubs and workplaces.<br/>Let’s turn your equipment vision into a plan.</p><button className="button outline-button" onClick={()=>request('business','Commercial gym fit-out')}>Start your project <ArrowUpRight size={18}/></button></div></section>
 </div>;
}
